# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build: # 一项叫做build的任务
    #runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    runs-on: windows-latest # 在最新版的Ubuntu系统下运行  

    
    steps:
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      #- name: Setup NuGet
       # uses: NuGet/setup-nuget@v1.0.2
      - name: Checkout # 将仓库内master分支的内容下载到工作目录
        uses: actions/checkout@v1 # 脚本来自 https://github.com/actions/checkout
      #- name: .NetFramework Action Template
       # uses: auycro/netframework-action-template@v0.0.2
      
      - name: Use Node.js 14.x # 配置Node环境
        uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
        with:
          node-version: "14.x"
      - name: Setup Hexo env
        run: |
          # set up private key for deploy
          #sudo apt-get install nasm
          #mkdir -p ~/.ssh/
          #echo "$HEXO_DEPLOY_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519  # 配置秘钥
          #chmod 600 ~/.ssh/id_ed25519
          #ssh-keyscan github.com >> ~/.ssh/known_hosts
          #ssh-keyscan gitee.com >> ~/.ssh/known_hosts
          # set git infomation
          #git config --global user.name 'linxiaoki'
          #git config --global user.email 'linxiaoki@foxmail.com'
          # install dependencies
          #npm install -g windows-build-tools
          npm install --global --production windows-build-tools --vs2015
          npm install -g node-gyp
          node-gyp install 14.15.4
          node install-node-deps.js
          npm install -g esy
          esy install
          esy bootstrap
          esy build
          esy run -f --checkhealth
     
